'use client';
import {FormEvent,useEffect,useState} from 'react';import {supabaseBrowser} from '../../../lib/supabase-browser';
export default function PlayerFields(){
 const [products,setProducts]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function token(){const {data}=await supabaseBrowser.auth.getSession();return data.session?.access_token||''}
 async function load(){const t=await token();const [p,s]=await Promise.all([fetch('/api/catalog/products?type=digital'),fetch('/api/admin/player-fields',{headers:{authorization:`Bearer ${t}`}})]);const [jp,js]=await Promise.all([p.json(),s.json()]);if(p.ok)setProducts(jp.products||[]);if(s.ok)setRows(js.schemas||[])}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),t=await token();const fields=[] as any[];if(f.get('playerId')==='on')fields.push({name:'playerId',label:'Player ID',required:true});if(f.get('serverId')==='on')fields.push({name:'serverId',label:'Server / Zone ID',required:false});if(f.get('nickname')==='on')fields.push({name:'nickname',label:'Nickname',required:false});const r=await fetch('/api/admin/player-fields',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${t}`},body:JSON.stringify({productId:f.get('productId'),fields})});const j=await r.json();setMsg(r.ok?'Field schema saved.':j.error);if(r.ok)load()}
 return <main className="adminStandalone"><div className="pageHead"><div><small>ADMIN / TOP-UP FIELDS</small><h1>Player Field Schemas</h1></div></div><div className="providerLayout"><form className="adminForm" onSubmit={submit}><label>Digital Product<select name="productId" required><option value="">Select</option>{products.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="check"><input name="playerId" type="checkbox" defaultChecked/> Player ID</label><label className="check"><input name="serverId" type="checkbox"/> Server / Zone ID</label><label className="check"><input name="nickname" type="checkbox"/> Nickname</label><button className="btnBlue">SAVE FIELDS</button>{msg&&<p>{msg}</p>}</form><div className="tableCard"><table><thead><tr><th>Product</th><th>Fields</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.products?.name}</td><td>{(x.fields||[]).map((f:any)=>f.label).join(', ')}</td></tr>)}</tbody></table></div></div></main>
}
