'use client';
import {FormEvent,useEffect,useState} from 'react';import {supabaseBrowser} from '../../../lib/supabase-browser';
export default function Providers(){
 const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function token(){const {data}=await supabaseBrowser.auth.getSession();return data.session?.access_token||''}
 async function load(){const t=await token();const r=await fetch('/api/admin/providers',{headers:{authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok)setRows(j.providers||[]);else setMsg(j.error)}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),t=await token();const body={name:f.get('name'),providerType:f.get('type'),priority:f.get('priority'),baseUrl:f.get('baseUrl'),keyEnv:f.get('keyEnv')};const r=await fetch('/api/admin/providers',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${t}`},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?'Provider created.':j.error);if(r.ok){e.currentTarget.reset();load()}}
 return <main className="adminStandalone"><div className="pageHead"><div><small>ADMIN / API</small><h1>API Providers</h1></div></div><div className="providerLayout"><form className="adminForm" onSubmit={submit}><h3>Add Provider</h3><label>Name<input name="name" required/></label><div className="two"><label>Type<select name="type"><option value="topup">Top-Up</option><option value="merchant">Merchant Payment</option></select></label><label>Priority<input name="priority" type="number" defaultValue="100"/></label></div><label>Base URL<input name="baseUrl" placeholder="https://api.provider.com"/></label><label>Secret Key Environment Name<input name="keyEnv" placeholder="TOPUP_API_KEY"/></label><button className="btnBlue">SAVE PROVIDER</button>{msg&&<p>{msg}</p>}</form><div className="tableCard"><table><thead><tr><th>Name</th><th>Type</th><th>Priority</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.provider_type}</td><td>{x.priority}</td><td>{x.is_active?'Active':'Disabled'}</td></tr>)}</tbody></table></div></div></main>
}
