'use client';
import {FormEvent,useEffect,useState} from 'react';import {supabaseBrowser} from '../../../lib/supabase-browser';
export default function SandboxTests(){
 const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function token(){const {data}=await supabaseBrowser.auth.getSession();return data.session?.access_token||''}
 async function load(){const t=await token();const r=await fetch('/api/admin/sandbox-tests',{headers:{authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok)setRows(j.tests||[])}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),t=await token();const r=await fetch('/api/admin/sandbox-tests',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${t}`},body:JSON.stringify({testType:f.get('testType'),status:f.get('status'),provider:f.get('provider'),reference:f.get('reference'),notes:f.get('notes')})});const j=await r.json();setMsg(r.ok?'Sandbox result saved.':j.error);if(r.ok){e.currentTarget.reset();load()}}
 return <main className="adminStandalone"><div className="pageHead"><div><small>ADMIN / SANDBOX</small><h1>Sandbox Test History</h1></div></div><div className="providerLayout"><form className="adminForm" onSubmit={submit}><label>Test Type<select name="testType"><option>payment_success</option><option>payment_failure</option><option>topup_success</option><option>topup_failure</option><option>refund</option><option>duplicate_callback</option></select></label><label>Status<select name="status"><option>passed</option><option>failed</option><option>pending</option></select></label><label>Provider<input name="provider"/></label><label>Reference<input name="reference"/></label><label>Notes<textarea name="notes"/></label><button className="btnBlue">SAVE TEST</button>{msg&&<p>{msg}</p>}</form><div className="tableCard"><table><thead><tr><th>Type</th><th>Status</th><th>Provider</th><th>Reference</th><th>Date</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.test_type}</td><td>{x.status}</td><td>{x.provider||'-'}</td><td>{x.reference||'-'}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></div></main>
}
