'use client';
import {FormEvent,useEffect,useState} from 'react';import {supabaseBrowser} from '../../lib/supabase-browser';
export default function ProductEditor({productId}:{productId:string}){
 const [product,setProduct]=useState<any>(null),[variants,setVariants]=useState<any[]>([]),[images,setImages]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[brands,setBrands]=useState<any[]>([]),[msg,setMsg]=useState('');
 async function token(){const {data}=await supabaseBrowser.auth.getSession();return data.session?.access_token||''}
 async function load(){const t=await token();const [p,v,c,b,full]=await Promise.all([
  fetch(`/api/admin/products/${productId}/base`,{headers:{authorization:`Bearer ${t}`}}).then(r=>r.json()),
  fetch(`/api/admin/products/${productId}/variants`,{headers:{authorization:`Bearer ${t}`}}).then(r=>r.json()),
  fetch('/api/admin/categories',{headers:{authorization:`Bearer ${t}`}}).then(r=>r.json()),
  fetch('/api/admin/brands',{headers:{authorization:`Bearer ${t}`}}).then(r=>r.json()),
  fetch(`/api/catalog/products/${product?.slug||'__none__'}`).then(r=>r.ok?r.json():({}))
 ]);setProduct(p.product||null);setVariants(v.variants||[]);setCategories(c.categories||[]);setBrands(b.brands||[]);
 if(p.product?.slug){const rr=await fetch(`/api/catalog/products/${p.product.slug}`);const jj=await rr.json();if(rr.ok)setImages(jj.product?.product_images||[])}
 }
 useEffect(()=>{load()},[]);
 async function authFetch(url:string,init:any={}){const t=await token();return fetch(url,{...init,headers:{...(init.headers||{}),authorization:`Bearer ${t}`}})}
 async function saveBase(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={name:f.get('name'),slug:f.get('slug'),description:f.get('description'),price:f.get('price'),cost_price:f.get('cost_price'),compare_at_price:f.get('compare_at_price'),category_id:f.get('category_id')||null,brand_id:f.get('brand_id')||null,is_featured:f.get('is_featured')==='on'};const r=await authFetch(`/api/admin/products/${productId}/base`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?'Product updated.':j.error);if(r.ok)load()}
 async function addVariant(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await authFetch(`/api/admin/products/${productId}/variants`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({variantName:f.get('name'),sku:f.get('sku'),price:f.get('price'),stock:f.get('stock')})});const j=await r.json();setMsg(r.ok?'Variant added.':j.error);if(r.ok){e.currentTarget.reset();load()}}
 async function editVariant(v:any){const variant_name=prompt('Variant name',v.variant_name||'');if(variant_name===null)return;const stock=prompt('Stock',String(v.stock??0));if(stock===null)return;const r=await authFetch(`/api/admin/products/${productId}/variants/${v.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({variant_name,stock:Number(stock)})});setMsg(r.ok?'Variant updated.':'Variant update failed');if(r.ok)load()}
 async function deleteVariant(id:string){if(!confirm('Delete this variant?'))return;const r=await authFetch(`/api/admin/products/${productId}/variants/${id}`,{method:'DELETE'});setMsg(r.ok?'Variant deleted.':'Delete failed');if(r.ok)load()}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);f.set('productId',productId);f.set('isPrimary',String(f.get('primary')==='on'));const r=await authFetch('/api/admin/storage/upload',{method:'POST',body:f});const j=await r.json();setMsg(r.ok?'Image uploaded.':j.error);if(r.ok){e.currentTarget.reset();load()}}
 async function deleteImage(id:string){if(!confirm('Delete this image?'))return;const r=await authFetch(`/api/admin/products/${productId}/images/${id}`,{method:'DELETE'});setMsg(r.ok?'Image deleted.':'Image delete failed');if(r.ok)load()}
 if(!product)return <div className="panel">Loading product...</div>;
 return <div className="editorStack">
  <form className="adminForm wideForm" onSubmit={saveBase}><h3>Product Details</h3><div className="two"><label>Name<input name="name" defaultValue={product.name}/></label><label>Slug<input name="slug" defaultValue={product.slug}/></label></div><div className="two"><label>Category<select name="category_id" defaultValue={product.category_id||''}><option value="">No category</option>{categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Brand<select name="brand_id" defaultValue={product.brand_id||''}><option value="">No brand</option>{brands.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></div><div className="three"><label>Price<input name="price" type="number" step="0.01" defaultValue={product.price}/></label><label>Cost<input name="cost_price" type="number" step="0.01" defaultValue={product.cost_price}/></label><label>Compare Price<input name="compare_at_price" type="number" step="0.01" defaultValue={product.compare_at_price||''}/></label></div><label>Description<textarea name="description" defaultValue={product.description||''}/></label><label className="check"><input name="is_featured" type="checkbox" defaultChecked={product.is_featured}/> Featured product</label><button className="btnBlue">SAVE PRODUCT</button></form>
  <div className="editorGrid"><form className="adminForm" onSubmit={addVariant}><h3>Add Variant</h3><label>Name<input name="name" placeholder="Black / Red Switch"/></label><label>SKU<input name="sku"/></label><div className="two"><label>Price<input name="price" type="number" step="0.01"/></label><label>Stock<input name="stock" type="number" defaultValue="0"/></label></div><button className="btnBlue">ADD VARIANT</button><div className="miniList">{variants.map(v=><p key={v.id}><b>{v.variant_name||'Default'}</b><span>{v.sku||'-'} • {v.stock} stock <button type="button" onClick={()=>editVariant(v)}>Edit</button> <button type="button" onClick={()=>deleteVariant(v.id)}>Delete</button></span></p>)}</div></form>
  <form className="adminForm" onSubmit={upload}><h3>Product Images</h3><label>Image<input name="file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" required/></label><label>Alt text<input name="altText"/></label><label className="check"><input name="primary" type="checkbox"/> Primary image</label><button className="btnBlue">UPLOAD IMAGE</button><div className="imageManager">{images.map((x:any)=><div key={x.id}><img src={x.url} alt={x.alt_text||''}/><button type="button" onClick={()=>deleteImage(x.id)}>Delete</button></div>)}</div></form></div>
  {msg&&<p>{msg}</p>}
 </div>
}
